version: '3.3'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  admin:
    depends_on:
      - mysqldb
    build: ./Admin
    restart: on-failure
    env_file: ./.env
    ports:
      - $ADMIN_LOCAL_PORT:$ADMIN_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m1:/root/.m1
    stdin_open: true
    tty: true
  appointment:
    depends_on:
      - mysqldb
    build: ./Appointment_Server
    restart: on-failure
    env_file: ./.env
    ports:
      - $APPOINTMENT_SERVER_LOCAL_PORT:$APPOINTMENT_SERVER_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
           "spring.datasource.username" : "$MYSQLDB_USER",
           "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  profile:
    depends_on:
      - mysqldb
    build: ./Profile
    restart: on-failure
    env_file: ./.env
    ports:
      - $PROFILE_LOCAL_PORT:$PROFILE_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
             "spring.datasource.username" : "$MYSQLDB_USER",
             "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
             "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
             "spring.jpa.hibernate.ddl-auto" : "update"
           }'
    volumes:
      - .m3:/root/.m3
    stdin_open: true
    tty: true

  sept_backend:
    depends_on:
      - mysqldb
    build: ./SEPT_Backend
    restart: on-failure
    env_file: ./.env
    ports:
      - $SEPT_BACKEND_LOCAL_PORT:$SEPT_BACKEND_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
             "spring.datasource.username" : "$MYSQLDB_USER",
             "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
             "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
             "spring.jpa.hibernate.ddl-auto" : "update"
           }'
    volumes:
      - .m4:/root/.m4
    stdin_open: true
    tty: true

    # test

  symptom:
    depends_on:
      - mysqldb
    build: ./symptom
    restart: on-failure
    env_file: ./.env
    ports:
      - $SYMPTOM_LOCAL_PORT:$SYMPTOM_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
             "spring.datasource.username" : "$MYSQLDB_USER",
             "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
             "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
             "spring.jpa.hibernate.ddl-auto" : "update"
           }'
    volumes:
      - .m5:/root/.m5
    stdin_open: true
    tty: true

volumes:
  db:


