- name: Deploy to Docker Host
  uses: wshihadeh/docker-deployment-action@v1
  with:
    remote_docker_host: root@188.166.255.31
    ssh_private_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDghYxqPsX8d0SLiSIK6yV95Z57N980/mFBVscuczE/fJZQgkxjsCtOOIriF3KRuIKgjyknXtE9iwWcCIlG8ZO1x+jq7N756rWYyKg3q3U+bTYwVd/DkoNLO+wy7G6PXwFh/5jHhdEQr4f2HxdspHwrKYdPvj/+7TBP/lssSuhU7F/qCB9pmK+bbWG1X4/Ndl2Le+PSgZfkmp55gsU2xVbcwhp4jhzEikdeD8JEYmwiwgn3GajnYF258hcdpbjoGoG/c+CL+VM8K8n2ITlnQYdqhSMyWhsVAOgkJlAs7KjQFi8uwTqyMGJwvR+odMzpk4Hw4+7o0oigld72gSggzTAayOyPUrA7Tr5lJA+upsZCWb1UAlJoR6fVZJ81z7Zt+1MEpTUVZ4Fjo96ABxkT62aIsiVUbsv6XC0IpWe2m6vilJG5lkmv4yHkBCLAGynWMWux5X5o+XaYPOi+Qvsn5jdfwEoF/pHGm6B+00Xpz0GYE2k663nIGF8e88o/kvMpWQs= hooniesun@192-168-1-170.tpgi.com.au
    ssh_public_key: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDp8Nn8M0
YJkhIS/kN1LYobAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQDghYxqPsX8
d0SLiSIK6yV95Z57N980/mFBVscuczE/fJZQgkxjsCtOOIriF3KRuIKgjyknXtE9iwWcCI
lG8ZO1x+jq7N756rWYyKg3q3U+bTYwVd/DkoNLO+wy7G6PXwFh/5jHhdEQr4f2HxdspHwr
KYdPvj/+7TBP/lssSuhU7F/qCB9pmK+bbWG1X4/Ndl2Le+PSgZfkmp55gsU2xVbcwhp4jh
zEikdeD8JEYmwiwgn3GajnYF258hcdpbjoGoG/c+CL+VM8K8n2ITlnQYdqhSMyWhsVAOgk
JlAs7KjQFi8uwTqyMGJwvR+odMzpk4Hw4+7o0oigld72gSggzTAayOyPUrA7Tr5lJA+ups
ZCWb1UAlJoR6fVZJ81z7Zt+1MEpTUVZ4Fjo96ABxkT62aIsiVUbsv6XC0IpWe2m6vilJG5
lkmv4yHkBCLAGynWMWux5X5o+XaYPOi+Qvsn5jdfwEoF/pHGm6B+00Xpz0GYE2k663nIGF
8e88o/kvMpWQsAAAWgw3nY/9vMmTt94nBQXkfS7Jze1WcYckgLoeEDjE7uPGx6RWHZvAOU
yaUYlyWOUJ8hF0C0c1hGjSwonWf3IcLFcYNZ8X0IZjF5Btb1MKHYti+oo4h0epAOmuMdIf
kvLz/coARt6jTg04R8U5753DnCV0SRZEqS05/JgvM2y8RztH/8ROxVknw//FqzXQjgrOVq
0MUkBJXQsXRL7buYNE9N9WXWkBJ1rZm4oTJi+eOPkAOBG/ybY1qPnDnrKhC7nsarTdsGC5
SiL8KBfZwssL6aVLL4FRODu8mhhr81tvtRDrhjBZAheJ/yq5tkbJXINijR96oa2D3eItR8
J/WDrwijkHs0AczxBhczP4yAOg32Djs/tYGIL3pGNlTKfyvzeaAFGFJx9KAUM5RcZX9zf4
Tyr90jE+YcsyGbiYuooVR6LfMSzLaL8geTeDJWn5LcZcITKKz1cfGA7UNHMKoVtNDzCdk2
MrUBRSqnIuVug+qdZYI+qrBQ6bcqAMtl4PnUR+Ewt89wP7Pzgp+kvQySPwpSKj7l8i+Mja
0NnUXnN5rgunVP6AkEy2vusJsAn1oxselsxdd2Em4Bmp0yS13ui12t5Zsy7xc6AHcn3rOv
Hif2eEh9t/HOmFAtubRnVKlxf9B259awAZQO8VpycxG3VyffSZeC6hZgNwLeiBVNda2WXN
5yqjEnUT4i0htyjgogL5Uld0u2KpGWhd81KPRq7bOiikCr3e/jsCkD9xgzaR+bvHKgf8Fw
9+X97pTZEjamI+oSfetiGcU6QHBoqrGmxOyoJC97sNXGIXuGm+Nojd0fGewLHj1zSUzf2d
2BEIjINOH+wnZV4be+aIuGTnYAH+4PrQE0h0HYEO2xORNnXB1QAQJXUqeBVDHjvhCifoLj
ICBMdN/MITK0EuAKs4Pnsh+XH294xouau4UsoKuLUxmol+FrgbtbQf/DVqrQDvM6LZNrwa
RsIDV1gvUulgizEMfi0kThM22fkYCGCDr0WMu7a1Nm/JO9QpDb6C7yEczS4cjgaqbgvhP7
z7WhIkHIM9VScTb5VqDE502cG2L8IZtPhXgccPlC/w+C0UIhVVkvaKjT3k0pqhVlf9s/PK
PMtRJ6JWtDnNzNGdzRSL2ZW8JuqwTZFGDLY+QDDhd1zgBGCV98WzcxPAZGFO4ov/Yt22Vj
gflpVUcwBxKoevn1v/pTtPqm1jsRpDiAAOrs3+/1AXMjAfY23NQv/h+H06wxCUHrS5yQCF
VIa6rYNHSW/QCaNFwVF8OP1VmhrgR4osAtdKGkW/yFthapOmpEF7/FmWvH/E6EUmxovd7t
pIbCTyN9fM4OOq/lCvH5VTEeCyNqlgzid32xqlYlmkT7PE4hwEkhBp5oC8lP3L3zBhY3nk
vwgqdFwNeJ+Ev9VcXlTm/iekq9yVp7Yd64r1V1SHDUncjYL3B8iVLRUf1al/mHSBA3cpUX
4GSUd2zyRWCOgvPN0VAcovCNhkBk2Fkf2S3QtPdT3IOSeFCzd4ibdz91HGvkTsFyuhKe4x
rqs8nUPgwIy0WI0M9kMydF+OG7tlVrrrHOvZ9bOloyFR6DNz4DynZR3cEBwEyZB51YlRg2
YFwfAaDTDTJ7cwbvpSbUG5yEyI5rRUgNj0oYc6NPOBGCXQKqA7ZSAWGem046lJUDhnzJrz
H9aUPpU9AGj+d9dZSI6I8z2doR9i+vAfQuP4Vdv1zFLl5msL65NsBNl2jIhAudyKKx289z
Hez1Ngcd9qrK6O76Us4+7Lr8XKk36iC+UA7/bIBf650WrniufbVlbtTF7sPMYD80mTwSVM
jK0JesNgJW1ZhlYYlnkYUCuzodIcqmDQ3RLtie/DOmq1phRaHnBVdNoTmkJu4lydM0a+cg
gzQgDjWBmFo9kzkyqw/n6i8p+Y3VUAcNinU4YQDdKpC2rhl5
    deployment_mode: docker-compose
    args: up -d
    pre_deployment_command_args: 'bundle exec rake db:migrate'
    docker_prune: 'true'
    pull_images_first: 'true'