name: docker-compose-multiple-apps-heroku-deploy #set whatevername you want to your github job
on:
  pull_request:
    branches:
      - docker_backend
  push:
    branches:
      - docker_backend # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0 # use the latest version of the action
        with:
          email: s3774430@student.rmit.edu.au # your heroku email
          api_key: da8fc1ed-129a-4e55-ae0b-0366801d9690 # your  heroku api key
          docker_compose_file: "Backend/docker-compose.yml" # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"mysql:8.0.30","appname":"sept-mysql","apptype":"web"},{"imagename":"backend-symptom:latest","appname":"sept-symptom","apptype":"web"},{"imagename":"backend-sept_backend:latest","appname":"sept-sept-backend","apptype":"worker"},{"imagename":"backend-appointment:latest ","appname":"sept-appointment","apptype":"web"},{"imagename":"backend-profile:latest","appname":"sept-profile","apptype":"web"},{"imagename":"backend-admin:latest","appname":"sept-admin","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
