name: Deploy

on:
  push:
    branches:
      - docker_backend
  pull_request:
    branches:
      - docker_backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@139.59.254.84
          ssh_private_key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAwKXIbOZ0UW9ZgzgkRKfov0NIGdwbNIzMuwfSGINTf/JlgO4oCeMS
q1zAxl1qHuWoTLCgpW5AYqz1QblGP0eI5xr1ojWQHgojvF/CHRA2t3CXunJ1oufHCDP95E
3WN92L/Jt9xoICkFh1XXPW47k9B3YI5xEBOWQ6f3YihnRis4R/TUD0ApPO6TjuL3BTmeVa
c0aVA9dl+n+wIfSiW+AjIaiLYKkIExnOV3rXaHsXTp+36cdyNeq691vm/Q8iqfLvHPOXYj
mZBf/vN681sldPbOsmNJ1+bT2nJzF1xSmLqEYUbCCcETIGMLc2FT+Jnt6l6bq1WXbG5d07
EkK0LCogflG1ahtDb0JRkYD1gPBJDvRwBJRvij1qAEXedTnqbrJkQ881Cbh/TmQAoSJN7C
WIXZ1dP1hX4QZCOUq+j7fTvLVUkMgXfMBdQWwtgJlWoju6a3budHJM/08idgHGBAGn8Qex
r+fLzmLxatQTOR0WG342/wHHYjy2SRlrxGuj0/ItAAAFmBz//U8c//1PAAAAB3NzaC1yc2
EAAAGBAMClyGzmdFFvWYM4JESn6L9DSBncGzSMzLsH0hiDU3/yZYDuKAnjEqtcwMZdah7l
qEywoKVuQGKs9UG5Rj9HiOca9aI1kB4KI7xfwh0QNrdwl7pydaLnxwgz/eRN1jfdi/ybfc
aCApBYdV1z1uO5PQd2COcRATlkOn92IoZ0YrOEf01A9AKTzuk47i9wU5nlWnNGlQPXZfp/
sCH0olvgIyGoi2CpCBMZzld612h7F06ft+nHcjXquvdb5v0PIqny7xzzl2I5mQX/7zevNb
JXT2zrJjSdfm09pycxdcUpi6hGFGwgnBEyBjC3NhU/iZ7epem6tVl2xuXdOxJCtCwqIH5R
tWobQ29CUZGA9YDwSQ70cASUb4o9agBF3nU56m6yZEPPNQm4f05kAKEiTewliF2dXT9YV+
EGQjlKvo+307y1VJDIF3zAXUFsLYCZVqI7umt27nRyTP9PInYBxgQBp/EHsa/ny85i8WrU
EzkdFht+Nv8Bx2I8tkkZa8Rro9PyLQAAAAMBAAEAAAGAc4X2vncj4YGoZ+vOs+0MwUUTg4
5eMhEM5Es4TcLS27L782jdUbB9jY09fLaf4I9PcU2pyAppScL1/8eevGulSRD9o5wDJEBo
VZoGyW7joPU/x2rD6ECdNeoXokSa5T1RqNWFgviLmQuytau1fTGjy0mY5RdpaIUWH0E0Sv
SYC5a00BrXOIRyW6DsFD6Do5HJv77ftUIBwUm40WPlyLqL1q8/hWNXmDytZAAiFGFcBKX6
n5Iehv6Px62wwqfE3azzc+vrGUefPZNqbER75NkIjDrRzIHEmy0cShTYqlmimsfGCWLHh3
jAYJ5SreZjRw5hUzatI7Nh2J9rlk+/BVlJumhq+T0+9JKmt3p2ITACbrkltZs/n+il3s+P
K0cIc+GxkL9W5np2XjJ2QaoRdBL8D5UNG30hUf+zekXKWMBFNBVE873wyFYBV/IX6KBWRg
O7zH1GmFAaiJCChOOh52naGscHjSny9XTyTQmOb1oOkbLh2KLIYPD6a85UiP3klUiBAAAA
wGTk/HtG82fJfICQqZyasT2wCWWBD1PsyQwJMyPhkeIulY7gz0KJ8lrSZB9Fjxp1Q3RMN6
k+/DUlq7AzaYMFf0McwxlUKeaMB35jcmRn6VKdDtCIl7I/HdTbYs0Vmo6lkgJdpjtoaHyY
Z0BvFc8d4IK6h6dSYTLzAjQGz+gEfs/3Mr4vVwr9NNXFefhXzUEUl0MFuQ8T16xkLQo1sh
0bySNQ5SqYv7SYRZWMgP4BxG1B7n0Hws880DCK6hZHHK4ujAAAAMEA6jtj86ob1gozF6Om
1EgUAjF8HJN10E+ejggY/+BhFLzwAQqEAcvNz0VmIJ0dL0TL17c+8oLlr/8EipWmU9twq8
mjpNsU5Ru3b1NGBp9wU1ldgckOMmVAX02FK5J05UmdXBT3LQxSyE3z9KgTLyQUzc5GenKW
h1JBQUNdDKpjYxcn0+oPc0sIxC/adrWWy6tMe6BGTkQm1doZvopH3HwHsU4Yz8WtazCE6N
AVu4jOSsR8oomJlG+CsG5rkkWT9SaJAAAAwQDSjQ7/cKlRgLEAV5afmOceGUbTM73024mN
+eWEhY7PmvWP5ekXtZZ1uX806Fmj4nD56Wd7jz3QNyQE2m9W2/flLHKVb8I9ORtAyVwF1O
aaVcK1pkS9OfcVblfqEQN/Lm2fGoVSW8kkWEE6UvgFYuZfrSItmhVcTVVnR5Qsm5ZqYb6D
roB6me2A1cTcB461EbUYI93dwMy1GO6gIfV4jsMA5YnXB6vMEqnHU07bggC1zNskjKmmws
iG+JffRlx0RYUAAAAjaG9vbmllc3VuQDE5Mi0xNjgtMS0xNzAudHBnaS5jb20uYXU=

          ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDApchs5nRRb1mDOCREp+i/Q0gZ3Bs0jMy7B9IYg1N/8mWA7igJ4xKrXMDGXWoe5ahMsKClbkBirPVBuUY/R4jnGvWiNZAeCiO8X8IdEDa3cJe6cnWi58cIM/3kTdY33Yv8m33GggKQWHVdc9bjuT0HdgjnEQE5ZDp/diKGdGKzhH9NQPQCk87pOO4vcFOZ5VpzRpUD12X6f7Ah9KJb4CMhqItgqQgTGc5XetdoexdOn7fpx3I16rr3W+b9DyKp8u8c85diOZkF/+83rzWyV09s6yY0nX5tPacnMXXFKYuoRhRsIJwRMgYwtzYVP4me3qXpurVZdsbl3TsSQrQsKiB+UbVqG0NvQlGRgPWA8EkO9HAElG+KPWoARd51OepusmRDzzUJuH9OZAChIk3sJYhdnV0/WFfhBkI5Sr6Pt9O8tVSQyBd8wF1BbC2AmVaiO7prdu50ckz/TyJ2AcYEAafxB7Gv58vOYvFq1BM5HRYbfjb/AcdiPLZJGWvEa6PT8i0= hooniesun@192-168-1-170.tpgi.com.au
          deployment_mode: docker-compose
          args: up -d
          pre_deployment_command_args: "bundle exec rake db:migrate"
          docker_prune: "true"
          pull_images_first: "true"
