name: Deploy

on:
  push:
    branches:
      - docker-test
  pull_request:
    branches:
      - docker-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: docker-test
      - run: |
          cd docker-test
          cd Backend
          ls

      - uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: root@165.232.172.169
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /root/my-deployment
          stack_file_name: docker-compose.yml
          keep_files: 10
          args: up -d
          docker_prune: "false"
          pull_images_first: "false"
      - run: |
          cd docker-test
          cd Backend
          ls
