name: docker-compose-multiple-apps-heroku-deploy #set whatevername you want to your github job
on:
  pull_request:
    branches:
      - docker_backend
  push:
    branches:
      - docker_backend # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0 # use the latest version of the action
        with:
          email: s3774430@student.rmit.edu.au # your heroku email
          api_key: da8fc1ed-129a-4e55-ae0b-0366801d9690 # your  heroku api key
          docker_compose_file: "Backend/docker-compose.yml" # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"f0d167a55aaf8a29fcff8e8718cb79bd88cb0f1214bbe1035c4843d27d5faab7","appname":"sept-mysql","apptype":"web"},{"imagename":"20e8cdd9205b83d9b4d3c42c2aa80b420d2f0df12b165651257ced1afc9af5f0","appname":"sept-symptom","apptype":"web"},{"imagename":"663e3143bb526cd4c6af0136a7072c2993184c6787892e77e87a7737dab96211","appname":"sept-sept-backend","apptype":"worker"},{"imagename":"b18b0f3bf65d1fd1df37f19090296bb69f162894c050ff714fcd1d94b8d1edb91","appname":"sept-appointment","apptype":"web"},{"imagename":"4f97ac23a2cd670e7d60b3b476368f2801f15421a28005c3048e29c92cb3ca0b","appname":"sept-profile","apptype":"web"},{"imagename":"bd7405f998b7368a51767be7697a46213ac95f0e03eaf8fbbc91ce0cffefdef6","appname":"sept-admin","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
