name: Deploy

on:
  push:
    branches:
      - docker_backend
  pull_request:
    branches:
      - docker_backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run bash
        run: ssh-keygen -R 188.166.220.203
        shell: bash
      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@188.166.220.203
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          args: up -d
          pre_deployment_command_args: "bundle exec rake db:migrate"
          docker_prune: "true"
          pull_images_first: "true"
