name: Deploy

on:
  push:
    branches:
      - docker-test
  pull_request:
    branches:
      - docker-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: docker-test
      - run: |
          cd docker-test
          cd Backend
          ls

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - run: |
          cd docker-test
          cd Backend
          ls
